"""likes

Revision ID: 2dcdf7a8e3a9
Revises: 505af87424b4
Create Date: 2025-05-11 12:16:01.165533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dcdf7a8e3a9'
down_revision: Union[str, None] = '505af87424b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('likes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('likes', 'movie_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('likes', 'comment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('comment', sa.VARCHAR(), nullable=True))
    op.alter_column('likes', 'movie_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('likes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
